/**
 * Demo/mock data for GitHub Pages static deployment.
 * The frontend detects when no backend is available and uses this data instead.
 */
import type { Student, StudentProfile } from '../types/student';
import type { User } from '../types/user';

export const DEMO_USERS: Record<string, { user: User; token: string }> = {
  admin: {
    user: {
      id: 'demo-admin-001',
      username: 'admin',
      full_name: '系统管理员',
      role: 'admin',
      is_active: true,
      created_at: '2026-01-01T00:00:00Z',
    },
    token: 'demo-token-admin',
  },
  XIAOCHENLAOSHI: {
    user: {
      id: 'demo-teacher-001',
      username: 'XIAOCHENLAOSHI',
      full_name: '小陈老师',
      role: 'teacher',
      is_active: true,
      email: 'xiaochen@school.edu.cn',
      school_id: 'demo-school-001',
      created_at: '2026-01-01T00:00:00Z',
    },
    token: 'demo-token-teacher1',
  },
  XIAOMINGLAOSHI: {
    user: {
      id: 'demo-teacher-002',
      username: 'XIAOMINGLAOSHI',
      full_name: '小明老师',
      role: 'teacher',
      is_active: true,
      email: 'xiaoming@school.edu.cn',
      school_id: 'demo-school-001',
      created_at: '2026-01-01T00:00:00Z',
    },
    token: 'demo-token-teacher2',
  },
  parent1: {
    user: {
      id: 'demo-parent-001',
      username: 'parent1',
      full_name: '王妈妈',
      role: 'parent',
      is_active: true,
      created_at: '2026-01-01T00:00:00Z',
    },
    token: 'demo-token-parent',
  },
};

export const DEMO_STUDENTS: Student[] = [
  {
    id: 'demo-stu-001',
    student_code: 'S2026001',
    full_name: '张小明',
    gender: 'male',
    birth_date: '2018-03-15',
    school_id: 'demo-school-001',
    current_class_id: 'demo-class-001',
    grade_level: 'G2',
    enrollment_date: '2024-09-01',
    family_structure: 'nuclear',
    is_active: true,
    risk_level: 'low',
    risk_score: 18.5,
    label_count: 2,
    created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'demo-stu-002',
    student_code: 'S2026002',
    full_name: '李小红',
    gender: 'female',
    birth_date: '2018-07-22',
    school_id: 'demo-school-001',
    current_class_id: 'demo-class-001',
    grade_level: 'G2',
    enrollment_date: '2024-09-01',
    family_structure: 'single_parent',
    special_needs: '注意力缺陷倾向',
    is_active: true,
    risk_level: 'high',
    risk_score: 62.3,
    label_count: 4,
    created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'demo-stu-003',
    student_code: 'S2026003',
    full_name: '王大力',
    gender: 'male',
    birth_date: '2017-11-08',
    school_id: 'demo-school-001',
    current_class_id: 'demo-class-001',
    grade_level: 'G2',
    enrollment_date: '2024-09-01',
    family_structure: 'grandparent_raised',
    medical_notes: '哮喘',
    is_active: true,
    risk_level: 'moderate',
    risk_score: 38.7,
    label_count: 3,
    created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'demo-stu-004',
    student_code: 'S2026004',
    full_name: '赵小美',
    gender: 'female',
    birth_date: '2018-01-30',
    school_id: 'demo-school-001',
    current_class_id: 'demo-class-001',
    grade_level: 'G2',
    enrollment_date: '2024-09-01',
    family_structure: 'nuclear',
    is_active: true,
    risk_level: 'low',
    risk_score: 12.1,
    label_count: 1,
    created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'demo-stu-005',
    student_code: 'S2026005',
    full_name: '陈小强',
    gender: 'male',
    birth_date: '2017-09-12',
    school_id: 'demo-school-001',
    current_class_id: 'demo-class-001',
    grade_level: 'G2',
    enrollment_date: '2024-09-01',
    family_structure: 'nuclear',
    medical_notes: '过敏性鼻炎',
    is_active: true,
    risk_level: 'critical',
    risk_score: 82.6,
    label_count: 5,
    created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'demo-stu-006',
    student_code: 'S2026006',
    full_name: '刘小花',
    gender: 'female',
    birth_date: '2018-05-18',
    school_id: 'demo-school-001',
    current_class_id: 'demo-class-001',
    grade_level: 'G2',
    enrollment_date: '2024-09-01',
    family_structure: 'nuclear',
    is_active: true,
    risk_level: 'low',
    risk_score: 9.8,
    label_count: 1,
    created_at: '2024-09-01T00:00:00Z',
  },
];

export const DEMO_STUDENT_PROFILES: Record<string, StudentProfile> = {
  'demo-stu-001': {
    ...DEMO_STUDENTS[0],
    labels: [
      { id: 'l1', name: '低风险正常', color: '#52c41a' },
      { id: 'l2', name: '同伴关系良好', color: '#36cfc9' },
    ],
    recent_observations: [
      { id: 'o1', observation_date: '2026-07-25', period: 'morning', context: 'classroom', mood_at_observation: 'happy' },
      { id: 'o2', observation_date: '2026-07-24', period: 'afternoon', context: 'playground', mood_at_observation: 'calm' },
      { id: 'o3', observation_date: '2026-07-23', period: 'all_day', context: 'classroom', mood_at_observation: 'happy' },
    ],
    recent_incidents: [],
  },
  'demo-stu-002': {
    ...DEMO_STUDENTS[1],
    labels: [
      { id: 'l3', name: '高风险预警', color: '#ff4d4f' },
      { id: 'l4', name: '注意力缺陷倾向', color: '#ff85c0' },
      { id: 'l5', name: '学习困难', color: '#ffc53d' },
      { id: 'l6', name: '情绪调节困难', color: '#ff7a45' },
    ],
    recent_observations: [
      { id: 'o4', observation_date: '2026-07-25', period: 'morning', context: 'classroom', mood_at_observation: 'anxious' },
      { id: 'o5', observation_date: '2026-07-24', period: 'all_day', context: 'classroom', mood_at_observation: 'neutral' },
    ],
    recent_incidents: [
      { id: 'i1', incident_date: '2026-07-22', incident_type: 'disruption', severity: 'minor', description: '上课时频繁离开座位' },
    ],
  },
};
